namespace IEPProject.Migrations
{
    using Data_Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<IEPProject.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "IEPProject.Models.ApplicationDbContext";
        }

        protected override void Seed(IEPProject.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //

            /*context.Parameters.AddOrUpdate(
                new Data_Models.PortalParameters { N = 3, D = 1000, S = 30, G = 50, P = 100, C = "EUR"}
            );*/

            /*context.Currencies.AddOrUpdate(
                c => c.Name,
                new Currency("Australia Dollar (AUD)"),
                new Currency("Great Britain Pound (GBP)"),
                new Currency("Euro (EUR)"),
                new Currency("Japan Yen (JPY)"),
                new Currency("Switzerland Franc (CHF)"),
                new Currency("USA Dollar (USD)"),
                new Currency("Afghanistan Afghani (AFN)"),
                new Currency("Albania Lek (ALL)"),
                new Currency("Algeria Dinar (DZD)"),
                new Currency("Angola Kwanza (AOA)"),
                new Currency("Argentina Peso (ARS)"),
                new Currency("Armenia Dram (AMD)"),
                new Currency("Aruba Florin (AWG)"),
                new Currency("Australia Dollar (AUD)"),
                new Currency("Austria Schilling (ATS)"),
                new Currency("Belgium Franc (BEF)"),
                new Currency("Azerbaijan New Manat (AZN)"),
                new Currency("Bahamas Dollar (BSD)"),
                new Currency("Bahrain Dinar (BHD)"),
                new Currency("Bangladesh Taka (BDT)"),
                new Currency("Barbados Dollar (BBD)"),
                new Currency("Belarus Ruble (BYR)"),
                new Currency("Belize Dollar (BZD)"),
                new Currency("Bermuda Dollar (BMD)"),
                new Currency("Bhutan Ngultrum (BTN)"),
                new Currency("Bolivia Boliviano (BOB)"),
                new Currency("Bosnia Mark (BAM)"),
                new Currency("Botswana Pula (BWP)"),
                new Currency("Brazil Real (BRL)"),
                new Currency("Great Britain Pound (GBP)"),
                new Currency("Brunei Dollar (BND)"),
                new Currency("Bulgaria Lev (BGN)"),
                new Currency("Burundi Franc (BIF)"),
                new Currency("CFA Franc BCEAO (XOF)"),
                new Currency("CFA Franc BEAC (XAF)"),
                new Currency("CFP Franc (XPF)"),
                new Currency("Cambodia Riel (KHR)"),
                new Currency("Canada Dollar (CAD)"),
                new Currency("Cape Verde Escudo (CVE)"),
                new Currency("Cayman Islands Dollar (KYD)"),
                new Currency("Chili Peso (CLP)"),
                new Currency("China Yuan/Renminbi (CNY)"),
                new Currency("Colombia Peso (COP)"),
                new Currency("Comoros Franc (KMF)"),
                new Currency("Congo Franc (CDF)"),
                new Currency("Costa Rica Colon (CRC)"),
                new Currency("Croatia Kuna (HRK)"),
                new Currency("Cuba Convertible Peso (CUC)"),
                new Currency("Cuba Peso (CUP)"),
                new Currency("Cyprus Pound (CYP)"),
                new Currency("Czech Koruna (CZK)"),
                new Currency("Denmark Krone (DKK)"),
                new Currency("Djibouti Franc (DJF)"),
                new Currency("Dominican Republich Peso (DOP)"),
                new Currency("East Caribbean Dollar (XCD)"),
                new Currency("Egypt Pound (EGP)"),
                new Currency("El Salvador Colon (SVC)"),
                new Currency("Estonia Kroon (EEK)"),
                new Currency("Ethiopia Birr (ETB)"),
                new Currency("Euro (EUR)"),
                new Currency("Falkland Islands Pound (FKP)"),
                new Currency("Finland Markka (FIM)"),
                new Currency("Fiji Dollar (FJD)"),
                new Currency("Gambia Dalasi (GMD)"),
                new Currency("Georgia Lari (GEL)"),
                new Currency("Germany Mark (DMK)"),
                new Currency("Ghana New Cedi (GHS)"),
                new Currency("Gibraltar Pound (GIP)"),
                new Currency("Greece Drachma (GRD)"),
                new Currency("Guatemala Quetzal (GTQ)"),
                new Currency("Guinea Franc (GNF)"),
                new Currency("Guyana Dollar (GYD)"),
                new Currency("Haiti Gourde (HTG)"),
                new Currency("Honduras Lempira (HNL)"),
                new Currency("Hong Kong Dollar (HKD)"),
                new Currency("Hungary Forint (HUF)"),
                new Currency("Iceland Krona (ISK)"),
                new Currency("India Rupee (INR)"),
                new Currency("Indonesia Rupiah (IDR)"),
                new Currency("Iran Rial (IRR)"),
                new Currency("Iraq Dinar (IQD)"),
                new Currency("Ireland Pound (IED)"),
                new Currency("Israel New Shekel (ILS)"),
                new Currency("Italy Lira (ITL)"),
                new Currency("Jamaica Dollar (JMD)"),
                new Currency("Japan Yen (JPY)"),
                new Currency("Jordan Dinar (JOD)"),
                new Currency("Kazakhstan Tenge (KZT)"),
                new Currency("Kenya Shilling (KES)"),
                new Currency("Kuwait Dinar (KWD)"),
                new Currency("Kyrgyzstan Som (KGS)"),
                new Currency("Laos Kip (LAK)"),
                new Currency("Latvia Lats (LVL)"),
                new Currency("Lebanon Pound (LBP)"),
                new Currency("Lesotho Loti (LSL)"),
                new Currency("Liberia Dollar (LRD)"),
                new Currency("Libya Dinar (LYD)"),
                new Currency("Lithuania Litas (LTL)"),
                new Currency("Luxembourg Franc (LUF)"),
                new Currency("Macau Pataca (MOP)"),
                new Currency("Macedonia Denar (MKD)"),
                new Currency("Malagasy Ariary (MGA)"),
                new Currency("Malawi Kwacha (MWK)"),
                new Currency("Malaysia Ringgit (MYR)"),
                new Currency("Maldives Rufiyaa (MVR)"),
                new Currency("Malta Lira (MTL)"),
                new Currency("Mauritania Ouguiya (MRO)"),
                new Currency("Mauritius Rupee (MUR)"),
                new Currency("Mexico Peso (MXN)"),
                new Currency("Moldova Leu (MDL)"),
                new Currency("Mongolia Tugrik (MNT)"),
                new Currency("Morocco Dirham (MAD)"),
                new Currency("Mozambique New Metical (MZN)"),
                new Currency("Myanmar Kyat (MMK)"),
                new Currency("NL Antilles Guilder (ANG)"),
                new Currency("Namibia Dollar (NAD)"),
                new Currency("Nepal Rupee (NPR)"),
                new Currency("Netherlands Guilder (NLG)"),
                new Currency("New Zealand Dollar (NZD)"),
                new Currency("Nicaragua Cordoba Oro (NIO)"),
                new Currency("Nigeria Naira (NGN)"),
                new Currency("North Korea Won (KPW)"),
                new Currency("Norway Kroner (NOK)"),
                new Currency("Oman Rial (OMR)"),
                new Currency("Pakistan Rupee (PKR)"),
                new Currency("Panama Balboa (PAB)"),
                new Currency("Papua New Guinea Kina (PGK)"),
                new Currency("Paraguay Guarani (PYG)"),
                new Currency("Peru Nuevo Sol (PEN)"),
                new Currency("Philippines Peso (PHP)"),
                new Currency("Poland Zloty (PLN)"),
                new Currency("Portugal Escudo (PTE)"),
                new Currency("Qatar Rial (QAR)"),
                new Currency("Romania New Lei (RON)"),
                new Currency("Russia Rouble (RUB)"),
                new Currency("Rwanda Franc (RWF)"),
                new Currency("Samoa Tala (WST)"),
                new Currency("Sao Tome/Principe Dobra (STD)"),
                new Currency("Saudi Arabia Riyal (SAR)"),
                new Currency("Serbia Dinar (RSD)"),
                new Currency("Seychelles Rupee (SCR)"),
                new Currency("Sierra Leone Leone (SLL)"),
                new Currency("Singapore Dollar (SGD)"),
                new Currency("Slovakia Koruna (SKK)"),
                new Currency("Slovenia Tolar (SIT)"),
                new Currency("Solomon Islands Dollar (SBD)"),
                new Currency("Somali Shilling (SOS)"),
                new Currency("South Africa Rand (ZAR)"),
                new Currency("South Korea Won (KRW)"),
                new Currency("Spain Peseta (ESP)"),
                new Currency("Sri Lanka Rupee (LKR)"),
                new Currency("St Helena Pound (SHP)"),
                new Currency("Sudan Pound (SDG)"),
                new Currency("Suriname Dollar (SRD)"),
                new Currency("Swaziland Lilangeni (SZL)"),
                new Currency("Sweden Krona (SEK)"),
                new Currency("Switzerland Franc (CHF)"),
                new Currency("Syria Pound (SYP)"),
                new Currency("Taiwan Dollar (TWD)"),
                new Currency("Tanzania Shilling (TZS)"),
                new Currency("Thailand Baht (THB)"),
                new Currency("Tonga Pa'anga (TOP)"),
                new Currency("Trinidad/Tobago Dollar (TTD)"),
                new Currency("Tunisia Dinar (TND)"),
                new Currency("Turkish New Lira (TRY)"),
                new Currency("Turkmenistan Manat (TMM)"),
                new Currency("USA Dollar (USD)"),
                new Currency("Uganda Shilling (UGX)"),
                new Currency("Ukraine Hryvnia (UAH)"),
                new Currency("Uruguay Peso (UYU)"),
                new Currency("United Arab Emirates Dirham (AED)"),
                new Currency("Vanuatu Vatu (VUV)"),
                new Currency("Venezuela Bolivar (VEB)"),
                new Currency("Vietnam Dong (VND)"),
                new Currency("Yemen Rial (YER)"),
                new Currency("Zambia Kwacha (ZMK)"),
                new Currency("Zimbabwe Dollar (ZWD)")                
            );*/
        }
    }
}
